<div id="admin">
    <h1>Page d'administration</h1>
    <nav>
        <button class="btn" data-id="0">Articles</button>
        <button class="btn" data-id="1">Commentaires</button>
        <button class="btn" data-id="2">Catégories</button>
        <button class="btn" data-id="3">Messages</button>
    </nav>
    
    <div id="content-admin"></div>

</div>
<script src="ASSETS/js/tabs.js"></script>