<h2>LISTE DES CONTACTS</h2>
<table id="contactTable">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Message</th>
            <th>Date</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($data as $item): ?>
            <tr>
                <td><?= htmlspecialchars( $item['id']) ?></td>
                <td><?= htmlspecialchars( $item['lastName']) ?></td>
                <td><?= htmlspecialchars( $item['firstName']) ?></td>
                <td><?= htmlspecialchars( $item['email']) ?></td>
                <td><?= htmlspecialchars( $item['message']) ?></td>
                <td><?= htmlspecialchars( $item['date']) ?></td>
                <td><a href="delContact.php?id=<?= htmlspecialchars( $item['id']) ?>"><i class="far fa-trash-alt"></i></a></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>