<form class="generic-form" method="post" action="validlogin.php">
    <fieldset>
        <ul>
            <li>
                <label for="login">Login :</label>
                <input type="text" name="login" id="login" />
            </li>
            <li>
                <label for="pssw">Password :</label>
                <input type="password" name="password" id="pssw" />
            </li>
            <li>
                <div class="g-recaptcha" data-sitekey="6LcDnqwUAAAAANBaS3o2aTK0zMkLc8PC4KrhhBAi"></div>
    		</li>
            <li>
                <input type="submit" id="button" value="OK" >
            </li>
        </ul>
    </fieldset>
</form>        